version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
